<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Your Personalized Fitness Plan</title>
    <style>
        body {
            font-family: 'Helvetica', 'Arial', sans-serif;
            line-height: 1.6;
            color: #333;
            margin: 0;
            padding: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #592fde;
            padding-bottom: 20px;
        }
        .header h1 {
            color: #592fde;
            margin-bottom: 5px;
        }
        .header p {
            color: #666;
            font-size: 16px;
        }
        .profile-section {
            background-color: #f8f9fa;
            padding: 15px;
            border-radius: 5px;
            margin-bottom: 25px;
        }
        .profile-section h2 {
            color: #333;
            font-size: 18px;
            margin-top: 0;
            margin-bottom: 15px;
            border-bottom: 1px solid #ddd;
            padding-bottom: 8px;
        }
        .profile-grid {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 10px;
        }
        .profile-item {
            margin-bottom: 8px;
        }
        .profile-item strong {
            font-weight: bold;
        }
        .plan-section {
            margin-bottom: 30px;
        }
        .plan-section h2 {
            color: #28a745;
            font-size: 18px;
            margin-bottom: 15px;
            border-bottom: 1px solid #ddd;
            padding-bottom: 8px;
        }
        .plan-content {
            white-space: pre-line;
            font-size: 14px;
        }
        .footer {
            text-align: center;
            margin-top: 40px;
            font-size: 12px;
            color: #666;
            border-top: 1px solid #ddd;
            padding-top: 15px;
        }
        @page {
            margin: 40px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>🏋️ Your Personalized 30-Day Fitness Plan</h1>
        <p>Designed based on your goals and preferences</p>
    </div>

    <div class="profile-section">
        <h2>Your Fitness Profile</h2>
        <div class="profile-grid">
            <div class="profile-item">
                <strong>Fitness Goal:</strong> {{ ucfirst(str_replace('_', ' ', $fitnessProfile->fitness_goals)) }}
            </div>
            <div class="profile-item">
                <strong>Fitness Level:</strong> {{ ucfirst($fitnessProfile->fitness_level) }}
            </div>
            <div class="profile-item">
                <strong>Workout Types:</strong> {{ implode(', ', json_decode($fitnessProfile->workout_types)) }}
            </div>
            <div class="profile-item">
                <strong>Workout Environment:</strong> {{ ucfirst($fitnessProfile->workout_environment) }}
            </div>
            <div class="profile-item">
                <strong>Workout Time:</strong> {{ str_replace('_', ' ', ucfirst($fitnessProfile->workout_time)) }}
            </div>
            <div class="profile-item">
                <strong>Workout Frequency:</strong> {{ str_replace('_', ' ', ucfirst($fitnessProfile->workout_frequency)) }}
            </div>
        </div>
    </div>

    <div class="plan-section">
        <h2>📝 Your AI-Generated Plan</h2>
        <div class="plan-content">
            {{ $fitnessPlanResult->ai_response }}
        </div>
    </div>

    <div class="footer">
        <p>Generated by LifeSync AI on {{ date('F j, Y') }}</p>
        <p>This plan is personalized based on your provided information. Consult with a healthcare professional before starting any new fitness regimen.</p>
    </div>
</body>
</html>
